routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'SensoryMastersController@index');

Auth::routes();

Route::resource('qa-sample-datas', 'QaSampleDatasController');
Route::resource('sensory-masters', 'SensoryMastersController');
Route::resource('sensory-tests', 'SensoryTestsController');
Route::resource('groups', 'GroupsController');
Route::resource('users', 'UsersController');
Route::resource('qa-samplings', 'QaSamplingsController');
Route::resource('test-suits', 'TestSuitsController');

Route::get('/qasample/upload', 'QaSamplingsController@upload');
Route::post('/qasample/uploadAction', 'QaSamplingsController@uploadAction');
Route::get('/qa/upload', 'QaSampleDatasController@upload');
Route::post('/qa/uploadAction', 'QaSampleDatasController@uploadAction');
Route::get('/sensory/generate', 'SensoryMastersController@generateTest');
Route::post('/sensory/generateAction', 'SensoryMastersController@generateTestAction');
Route::get('/sensory/editset/{id}', 'SensoryMastersController@editset');
Route::post('/sensory/editsetAction/{id}', 'SensoryMastersController@editsetAction');
Route::get('/sensory/startTest/{id}', 'SensoryMastersController@startTest');
Route::get('/sensory/stopTest/{id}', 'SensoryMastersController@stopTest');
Route::get('/sensory/endTest/{id}', 'SensoryMastersController@endTest');
Route::get('/sensory/printform/{id}', 'SensoryMastersController@printform');


Route::get('/sensory/submitTest/{id}', 'SensoryMastersController@submitTest');
Route::post('/sensory/submitAction/{id}', 'SensoryMastersController@submitTestAction');
Route::get('/sensory/runtest/{id}', 'SensoryTestsController@runtest');
Route::post('/sensory/runtestAction/{id}', 'SensoryTestsController@runtestAction');
Route::get('/sensory/edittest/{id}', 'SensoryTestsController@edittest');
Route::post('/sensory/edittestAction/{id}', 'SensoryTestsController@edittestAction');
Route::get('/sensory/viewtest/{id}', 'SensoryTestsController@viewtest');
Route::get('/sensory/sendtest/{id}', 'SensoryTestsController@sendtest');
Route::get('/sensory/listsurvey/{id}', 'SensoryTestsController@listsurvey');

Route::get('/reports/summaryreport/{id}', 'ReportsController@summaryreport');
Route::get('/reports/xlssummaryreport/{id}', 'ReportsController@xlsreport');
Route::get('/reports/rangereport', 'ReportsController@rangereport');
Route::post('/reports/rangereportAction', 'ReportsController@rangereportAction');

Route::get('/test-suits/changeStatus/{id}/{status}', 'TestSuitsController@changeStatus');
Route::get('/test-suits/runtest/{test_suit_m_id}', 'TestSuitsController@runtest');
Route::post('/test-suits/runtestAction/{test_suit_m_id}', 'TestSuitsController@runtestAction');
Route::get('/test-suits/confirmtest/{ans_suit_m_id}', 'TestSuitsController@confirmtest');
Route::get('/test-suits/confirmtestAction/{ans_suit_m_id}', 'TestSuitsController@confirmtestAction');
Route::get('/test-suits/edittest/{ans_suit_m_id}', 'TestSuitsController@edittest');
Route::post('/test-suits/edittestAction/{ans_suit_m_id}', 'TestSuitsController@edittestAction');
Route::get('/test-suits/showResult/{test_suit_m_id}', 'TestSuitsController@showResult');
Route::get('/test-suits/exportExcel/{test_suit_m_id}', 'TestSuitsController@exportExcel');
Route::get('/test-suits/printform/{id}', 'TestSuitsController@printform');

Route::get('storage/capture/{id}/{filename}', function ($id,$filename) {
    $path = storage_path( 'app/capture/' . $id .'/'. $filename);

    if (!File::exists($path)) {
        abort(404);
    }

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        QA Sensory Test
                    </a>
                </div>

                @include('layouts.menu')
                
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('/js/app.js') }}"></script>
    <script src="{{ asset('/js/sensory.js?ver=3') }}"></script>
    <script src="{{ asset('/dist/js/multiselect.js') }}"></script>

</body>
</html>

resources/views/layouts/form.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        QA Sensory Test
                    </a>
                </div>
                
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('/js/app.js') }}"></script>
    <script src="{{ asset('/js/sensory.js?ver=3') }}"></script>
    <script src="{{ asset('/dist/js/multiselect.js') }}"></script>

</body>
</html>

resources/views/layouts/graph.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        QA Sensory Test
                    </a>
                </div>

                @include('layouts.menu')
                
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('/js/app.js') }}"></script>

</body>
</html>

resources/views/layouts/menu.blade.php
<div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->laconame }} - {{App\User::find(Auth::user()->id)->group->name}} <span class="caret"></span>
                                </a>
                            
                                @if ( App\User::find(Auth::user()->id)->group->role == 'admin'  )
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                    <a href="{{route('qa-samplings.index')}}">QA Sample Data</a>
                                    </li>
                                    <li>
                                    <a href="{{route('sensory-masters.index')}}">Sensory Test</a>
                                    </li>
                                    <li>
                                    <a href="{{route('test-suits.index')}}">Sensory Test 2</a>
                                    </li>
                                    <li>
                                    <a href="{{route('users.index')}}">User</a>
                                    </li>
                                    <li><hr/></li>
                                    <li>
                                    <a href="{{route('sensory-masters.index')}}">Daily Report</a>
                                    </li>
                                    <li>
                                    <a href="{{url('reports/rangereport')}}">Range Report</a>
                                    </li>
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                                @else
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                    <a href="{{route('qa-samplings.index')}}">QA Sample Data</a>
                                    </li>
                                    <li>
                                    <a href="{{route('sensory-masters.index')}}">Sensory Test</a>
                                    </li>
                                    <li>
                                    <a href="{{route('test-suits.index')}}">Sensory Test 2</a>
                                    </li>
                                    <li><hr/></li>
                                    <li>
                                    <a href="{{route('sensory-masters.index')}}">Daily Report</a>
                                    </li>
                                    <li>
                                    <a href="{{url('reports/rangereport')}}">Range Report</a>
                                    </li>
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                                @endif
                            </li>
                        @endif
                    </ul>
                </div>

resources/views/layouts/multiselect.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        QA Sensory Test
                    </a>
                </div>

                @include('layouts.menu')

            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
    <script src="{{ asset('dist/js/multiselect.js') }}"></script>
    <script>
$(document).ready(function() {
    // make code pretty

    $('#search').multiselect({
        search: {
            left: '<input type="text" name="q" class="form-control" placeholder="Search..." />',
            right: '<input type="text" name="q" class="form-control" placeholder="Search..." />',
        },
        fireSearch: function(value) {
            return value.length > 2;
        }
    });
});
</script>

</body>
</html>

resources/views/layouts/notlogin.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        QA Sensory Test
                    </a>
                </div>
                
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('/js/app.js') }}"></script>
    <script src="{{ asset('/js/sensory.js?ver=3') }}"></script>
    <script src="{{ asset('/dist/js/multiselect.js') }}"></script>

</body>
</html>

resources/views/layouts/print.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
<style> 
    @media print {
   @page {
      margin: 0;
    }
    body {
        height: 100%;
        width: 100%;
    }
    div.row > div {
      display: inline-block;  
      border: solid 1px #ccc;
      margin: 0.1cm;
      font-size: 1rem;
    }
    div.row {
      display: block;
      margin: solid 2px black;
      margin: 0.2cm 1cm;
      font-size: 0;
      white-space: nowrap;
    }
    .table {
        transform: translate(8.5in, -100%) rotate(90deg);
        transform-origin: bottom left;
        display: block;
    }

    }
</style>

</head>
<body>
        @yield('content')
</body>
</html>